# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from datetime import datetime
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


TriggerExecutionStatus = Union[
    Literal[
        "in_progress",
        "completed",
        "failed",
        "skipped",
        "timed_out",
    ],
    UnrecognizedStr,
]
r"""Output only. The status of the execution."""


class TriggerExecutionTypedDict(TypedDict):
    r"""An execution instance of a trigger."""

    id: str
    r"""Required. Output only. Identifier. The ID of the trigger execution."""
    trigger_id: str
    r"""Required. Output only. Identifier. The ID of the trigger that created this execution."""
    end_time: NotRequired[datetime]
    r"""Output only. The time when the execution finished."""
    environment_id: NotRequired[str]
    r"""Output only. The environment ID used for the execution."""
    error: NotRequired[str]
    r"""Output only. The error message if the execution failed."""
    interaction_id: NotRequired[str]
    r"""Output only. The ID of the interaction created by this execution, if any."""
    scheduled_time: NotRequired[datetime]
    r"""Output only. The time when the execution was scheduled to run."""
    start_time: NotRequired[datetime]
    r"""Output only. The time when the execution started."""
    status: NotRequired[TriggerExecutionStatus]
    r"""Output only. The status of the execution."""


class TriggerExecution(BaseModel):
    r"""An execution instance of a trigger."""

    id: str
    r"""Required. Output only. Identifier. The ID of the trigger execution."""

    trigger_id: str
    r"""Required. Output only. Identifier. The ID of the trigger that created this execution."""

    end_time: Optional[datetime] = None
    r"""Output only. The time when the execution finished."""

    environment_id: Optional[str] = None
    r"""Output only. The environment ID used for the execution."""

    error: Optional[str] = None
    r"""Output only. The error message if the execution failed."""

    interaction_id: Optional[str] = None
    r"""Output only. The ID of the interaction created by this execution, if any."""

    scheduled_time: Optional[datetime] = None
    r"""Output only. The time when the execution was scheduled to run."""

    start_time: Optional[datetime] = None
    r"""Output only. The time when the execution started."""

    status: Optional[TriggerExecutionStatus] = None
    r"""Output only. The status of the execution."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "end_time",
                "environment_id",
                "error",
                "interaction_id",
                "scheduled_time",
                "start_time",
                "status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
