# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import Base64EncodedString, Base64FileInput, BaseModel, UNSET_SENTINEL
from ...utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class CodeExecutionResultStepParam(TypedDict):
    r"""Code execution result step."""

    call_id: str
    r"""Required. ID to match the ID from the function call block."""
    result: str
    r"""Required. The output of the code execution."""
    is_error: NotRequired[bool]
    r"""Whether the code execution resulted in an error."""
    signature: NotRequired[Union[str, Base64FileInput]]
    r"""A signature hash for backend validation."""
    type: Literal["code_execution_result"]


class CodeExecutionResultStep(BaseModel):
    r"""Code execution result step."""

    call_id: str
    r"""Required. ID to match the ID from the function call block."""

    result: str
    r"""Required. The output of the code execution."""

    is_error: Optional[bool] = None
    r"""Whether the code execution resulted in an error."""

    signature: Optional[Base64EncodedString] = None
    r"""A signature hash for backend validation."""

    type: Annotated[
        Annotated[
            Literal["code_execution_result"],
            AfterValidator(validate_const("code_execution_result")),
        ],
        pydantic.Field(alias="type"),
    ] = "code_execution_result"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["is_error", "signature"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CodeExecutionResultStep.model_rebuild()
except NameError:
    pass
