# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from ...utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


DocumentDeltaMimeType = Union[
    Literal[
        "application/pdf",
        "text/csv",
    ],
    UnrecognizedStr,
]


class DocumentDeltaTypedDict(TypedDict):
    data: NotRequired[str]
    mime_type: NotRequired[DocumentDeltaMimeType]
    type: Literal["document"]
    uri: NotRequired[str]


class DocumentDelta(BaseModel):
    data: Optional[str] = None

    mime_type: Optional[DocumentDeltaMimeType] = None

    type: Annotated[
        Annotated[Literal["document"], AfterValidator(validate_const("document"))],
        pydantic.Field(alias="type"),
    ] = "document"

    uri: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "mime_type", "uri"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    DocumentDelta.model_rebuild()
except NameError:
    pass
