# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from ...utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FileSearchParam(TypedDict):
    r"""A tool that can be used by the model to search files."""

    file_search_store_names: NotRequired[List[str]]
    r"""The file search store names to search."""
    metadata_filter: NotRequired[str]
    r"""Metadata filter to apply to the semantic retrieval documents and chunks."""
    top_k: NotRequired[int]
    r"""The number of semantic retrieval chunks to retrieve."""
    type: Literal["file_search"]


class FileSearch(BaseModel):
    r"""A tool that can be used by the model to search files."""

    file_search_store_names: Optional[List[str]] = None
    r"""The file search store names to search."""

    metadata_filter: Optional[str] = None
    r"""Metadata filter to apply to the semantic retrieval documents and chunks."""

    top_k: Optional[int] = None
    r"""The number of semantic retrieval chunks to retrieve."""

    type: Annotated[
        Annotated[
            Literal["file_search"], AfterValidator(validate_const("file_search"))
        ],
        pydantic.Field(alias="type"),
    ] = "file_search"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["file_search_store_names", "metadata_filter", "top_k"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    FileSearch.model_rebuild()
except NameError:
    pass
