# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from ...utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, Dict, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FileCitationParam(TypedDict):
    r"""A file citation annotation."""

    custom_metadata: NotRequired[Dict[str, Any]]
    r"""User provided metadata about the retrieved context."""
    document_uri: NotRequired[str]
    r"""The URI of the file."""
    end_index: NotRequired[int]
    r"""End of the attributed segment, exclusive."""
    file_name: NotRequired[str]
    r"""The name of the file."""
    media_id: NotRequired[str]
    r"""Media ID in-case of image citations, if applicable."""
    page_number: NotRequired[int]
    r"""Page number of the cited document, if applicable."""
    source: NotRequired[str]
    r"""Source attributed for a portion of the text."""
    start_index: NotRequired[int]
    r"""Start of segment of the response that is attributed to this source.

    Index indicates the start of the segment, measured in bytes.
    """
    type: Literal["file_citation"]


class FileCitation(BaseModel):
    r"""A file citation annotation."""

    custom_metadata: Optional[Dict[str, Any]] = None
    r"""User provided metadata about the retrieved context."""

    document_uri: Optional[str] = None
    r"""The URI of the file."""

    end_index: Optional[int] = None
    r"""End of the attributed segment, exclusive."""

    file_name: Optional[str] = None
    r"""The name of the file."""

    media_id: Optional[str] = None
    r"""Media ID in-case of image citations, if applicable."""

    page_number: Optional[int] = None
    r"""Page number of the cited document, if applicable."""

    source: Optional[str] = None
    r"""Source attributed for a portion of the text."""

    start_index: Optional[int] = None
    r"""Start of segment of the response that is attributed to this source.

    Index indicates the start of the segment, measured in bytes.
    """

    type: Annotated[
        Annotated[
            Literal["file_citation"], AfterValidator(validate_const("file_citation"))
        ],
        pydantic.Field(alias="type"),
    ] = "file_citation"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "custom_metadata",
                "document_uri",
                "end_index",
                "file_name",
                "media_id",
                "page_number",
                "source",
                "start_index",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    FileCitation.model_rebuild()
except NameError:
    pass
