# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import (
    Base64EncodedString,
    Base64FileInput,
    BaseModel,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from ...utils import validate_const
from .googlesearchcallarguments import (
    GoogleSearchCallArguments,
    GoogleSearchCallArgumentsParam,
)
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


GoogleSearchCallStepSearchType = Union[
    Literal[
        "web_search",
        "image_search",
        "enterprise_web_search",
    ],
    UnrecognizedStr,
]
r"""The type of search grounding enabled."""


class GoogleSearchCallStepParam(TypedDict):
    r"""Google Search call step."""

    arguments: GoogleSearchCallArgumentsParam
    r"""The arguments to pass to Google Search."""
    id: str
    r"""Required. A unique ID for this specific tool call."""
    search_type: NotRequired[GoogleSearchCallStepSearchType]
    r"""The type of search grounding enabled."""
    signature: NotRequired[Union[str, Base64FileInput]]
    r"""A signature hash for backend validation."""
    type: Literal["google_search_call"]


class GoogleSearchCallStep(BaseModel):
    r"""Google Search call step."""

    arguments: GoogleSearchCallArguments
    r"""The arguments to pass to Google Search."""

    id: str
    r"""Required. A unique ID for this specific tool call."""

    search_type: Optional[GoogleSearchCallStepSearchType] = None
    r"""The type of search grounding enabled."""

    signature: Optional[Base64EncodedString] = None
    r"""A signature hash for backend validation."""

    type: Annotated[
        Annotated[
            Literal["google_search_call"],
            AfterValidator(validate_const("google_search_call")),
        ],
        pydantic.Field(alias="type"),
    ] = "google_search_call"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["search_type", "signature"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GoogleSearchCallStep.model_rebuild()
except NameError:
    pass
