# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from ...utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GoogleMapsParam(TypedDict):
    r"""A tool that can be used by the model to call Google Maps."""

    enable_widget: NotRequired[bool]
    r"""Whether to return a widget context token in the tool call result of the
    response.
    """
    latitude: NotRequired[float]
    r"""The latitude of the user's location."""
    longitude: NotRequired[float]
    r"""The longitude of the user's location."""
    type: Literal["google_maps"]


class GoogleMaps(BaseModel):
    r"""A tool that can be used by the model to call Google Maps."""

    enable_widget: Optional[bool] = None
    r"""Whether to return a widget context token in the tool call result of the
    response.
    """

    latitude: Optional[float] = None
    r"""The latitude of the user's location."""

    longitude: Optional[float] = None
    r"""The longitude of the user's location."""

    type: Annotated[
        Annotated[
            Literal["google_maps"], AfterValidator(validate_const("google_maps"))
        ],
        pydantic.Field(alias="type"),
    ] = "google_maps"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enable_widget", "latitude", "longitude"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GoogleMaps.model_rebuild()
except NameError:
    pass
