# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


GroundingToolCountType = Union[
    Literal[
        "google_search",
        "google_maps",
        "retrieval",
    ],
    UnrecognizedStr,
]
r"""The grounding tool type associated with the count."""


class GroundingToolCountTypedDict(TypedDict):
    r"""The number of grounding tool counts."""

    count: NotRequired[int]
    r"""The number of grounding tool counts."""
    type: NotRequired[GroundingToolCountType]
    r"""The grounding tool type associated with the count."""


class GroundingToolCount(BaseModel):
    r"""The number of grounding tool counts."""

    count: Optional[int] = None
    r"""The number of grounding tool counts."""

    type: Optional[GroundingToolCountType] = None
    r"""The grounding tool type associated with the count."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["count", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
