# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from ...utils import validate_const
from .interactionsseeventinteraction import (
    InteractionSseEventInteraction,
    InteractionSseEventInteractionTypedDict,
)
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InteractionCreatedEventTypedDict(TypedDict):
    interaction: InteractionSseEventInteractionTypedDict
    r"""Partial interaction resource emitted by interaction lifecycle SSE events.
    Streaming lifecycle payloads may omit fields that are only available on
    full non-streaming Interaction responses.

    """
    event_type: Literal["interaction.created"]
    event_id: NotRequired[str]
    r"""The event_id token to be used to resume the interaction stream, from
    this event.
    """


class InteractionCreatedEvent(BaseModel):
    interaction: InteractionSseEventInteraction
    r"""Partial interaction resource emitted by interaction lifecycle SSE events.
    Streaming lifecycle payloads may omit fields that are only available on
    full non-streaming Interaction responses.

    """

    event_type: Annotated[
        Annotated[
            Literal["interaction.created"],
            AfterValidator(validate_const("interaction.created")),
        ],
        pydantic.Field(alias="event_type"),
    ] = "interaction.created"

    event_id: Optional[str] = None
    r"""The event_id token to be used to resume the interaction stream, from
    this event.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["event_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    InteractionCreatedEvent.model_rebuild()
except NameError:
    pass
