# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import UnrecognizedStr
from typing import Literal, Union


Model = Union[
    Literal[
        # Our first hybrid reasoning model which supports a 1M token context window and has thinking budgets.
        "gemini-2.5-flash",
        # Our state-of-the-art multipurpose model, which excels at coding and complex reasoning tasks.
        "gemini-2.5-pro",
        # Gemma 4 26B A4B IT
        "gemma-4-26b-a4b-it",
        # Gemma 4 31B IT
        "gemma-4-31b-it",
        # Latest release of Gemini Flash
        "gemini-flash-latest",
        # Latest release of Gemini Flash-Lite
        "gemini-flash-lite-latest",
        # Latest release of Gemini Pro
        "gemini-pro-latest",
        # Our smallest and most cost effective model, built for at scale usage.
        "gemini-2.5-flash-lite",
        # Our native image generation model, optimized for speed, flexibility, and contextual understanding. Text input and output is priced the same as 2.5 Flash.
        "gemini-2.5-flash-image",
        # Our most intelligent model built for speed, combining frontier intelligence with superior search and grounding.
        "gemini-3-flash-preview",
        # Our latest SOTA reasoning model with unprecedented depth and nuance, and powerful multimodal understanding and coding capabilities.
        "gemini-3.1-pro-preview",
        # Gemini 3.1 Pro Preview optimized for custom tool usage
        "gemini-3.1-pro-preview-customtools",
        # Our most cost-efficient model, optimized for high-volume agentic tasks, translation, and simple data processing.
        "gemini-3.1-flash-lite",
        # Gemini 3 Pro Image
        "gemini-3-pro-image",
        # Gemini 3 Pro Image Preview
        "nano-banana-pro-preview",
        # Gemini 3.1 Flash Image.
        "gemini-3.1-flash-image",
        # Our most intelligent model for sustained frontier performance in agentic and coding tasks.
        "gemini-3.5-flash",
        # Our most intelligent model for sustained frontier performance in agentic and coding tasks.
        "gemini-3.6-flash",
        # Our most intelligent model for sustained frontier performance in agentic and coding tasks.
        "gemini-3.7-flash",
        # Our low-latency, music generation model optimized for high-fidelity audio clips and precise rhythmic control.
        "lyria-3-clip-preview",
        # Our advanced, full-song generative model with deep compositional understanding, optimized for precise structural control and complex transitions across diverse musical styles.
        "lyria-3-pro-preview",
        # Gemini Robotics-ER 1.6 Preview
        "gemini-robotics-er-1.6-preview",
        # Gemini Robotics Embodied Reasoning 2 Preview
        "gemini-robotics-er-2-preview",
    ],
    UnrecognizedStr,
]
r"""The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details."""
