# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class ParallelAISearchConfigParam(TypedDict):
    r"""Used to specify configuration for ParallelAISearch."""

    api_key: NotRequired[str]
    r"""Optional. The API key for ParallelAiSearch."""
    custom_config: NotRequired[Dict[str, Any]]
    r"""Optional. Custom configs for ParallelAiSearch."""


class ParallelAISearchConfig(BaseModel):
    r"""Used to specify configuration for ParallelAISearch."""

    api_key: Optional[str] = None
    r"""Optional. The API key for ParallelAiSearch."""

    custom_config: Optional[Dict[str, Any]] = None
    r"""Optional. Custom configs for ParallelAiSearch."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["api_key", "custom_config"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
