# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from ...utils import validate_const
from .reviewsnippet import ReviewSnippet, ReviewSnippetParam
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlaceCitationParam(TypedDict):
    r"""A place citation annotation."""

    end_index: NotRequired[int]
    r"""End of the attributed segment, exclusive."""
    name: NotRequired[str]
    r"""Title of the place."""
    place_id: NotRequired[str]
    r"""The ID of the place, in `places/{place_id}` format."""
    review_snippets: NotRequired[List[ReviewSnippetParam]]
    r"""Snippets of reviews that are used to generate answers about the
    features of a given place in Google Maps.
    """
    start_index: NotRequired[int]
    r"""Start of segment of the response that is attributed to this source.

    Index indicates the start of the segment, measured in bytes.
    """
    type: Literal["place_citation"]
    url: NotRequired[str]
    r"""URI reference of the place."""


class PlaceCitation(BaseModel):
    r"""A place citation annotation."""

    end_index: Optional[int] = None
    r"""End of the attributed segment, exclusive."""

    name: Optional[str] = None
    r"""Title of the place."""

    place_id: Optional[str] = None
    r"""The ID of the place, in `places/{place_id}` format."""

    review_snippets: Optional[List[ReviewSnippet]] = None
    r"""Snippets of reviews that are used to generate answers about the
    features of a given place in Google Maps.
    """

    start_index: Optional[int] = None
    r"""Start of segment of the response that is attributed to this source.

    Index indicates the start of the segment, measured in bytes.
    """

    type: Annotated[
        Annotated[
            Literal["place_citation"], AfterValidator(validate_const("place_citation"))
        ],
        pydantic.Field(alias="type"),
    ] = "place_citation"

    url: Optional[str] = None
    r"""URI reference of the place."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["end_index", "name", "place_id", "review_snippets", "start_index", "url"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PlaceCitation.model_rebuild()
except NameError:
    pass
