# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from ...utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RankingParam(TypedDict):
    r"""Config for Rank Service."""

    model_name: NotRequired[str]
    r"""Optional. The model name of the rank service."""
    ranking_config: Literal["rank_service"]


class Ranking(BaseModel):
    r"""Config for Rank Service."""

    model_name: Optional[str] = None
    r"""Optional. The model name of the rank service."""

    ranking_config: Annotated[
        Annotated[
            Literal["rank_service"], AfterValidator(validate_const("rank_service"))
        ],
        pydantic.Field(alias="ranking_config"),
    ] = "rank_service"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["model_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Ranking.model_rebuild()
except NameError:
    pass
