# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class StatusParam(TypedDict):
    r"""The `Status` type defines a logical error model that is suitable for
    different programming environments, including REST APIs and RPC APIs. It is
    used by [gRPC](https://github.com/grpc). Each `Status` message contains
    three pieces of data: error code, error message, and error details.

    You can find out more about this error model and how to work with it in the
    [API Design Guide](https://cloud.google.com/apis/design/errors).
    """

    code: NotRequired[int]
    r"""The status code, which should be an enum value of google.rpc.Code."""
    details: NotRequired[List[Dict[str, Any]]]
    r"""A list of messages that carry the error details.  There is a common set of
    message types for APIs to use.
    """
    message: NotRequired[str]
    r"""A developer-facing error message, which should be in English. Any
    user-facing error message should be localized and sent in the
    google.rpc.Status.details field, or localized by the client.
    """


class Status(BaseModel):
    r"""The `Status` type defines a logical error model that is suitable for
    different programming environments, including REST APIs and RPC APIs. It is
    used by [gRPC](https://github.com/grpc). Each `Status` message contains
    three pieces of data: error code, error message, and error details.

    You can find out more about this error model and how to work with it in the
    [API Design Guide](https://cloud.google.com/apis/design/errors).
    """

    code: Optional[int] = None
    r"""The status code, which should be an enum value of google.rpc.Code."""

    details: Optional[List[Dict[str, Any]]] = None
    r"""A list of messages that carry the error details.  There is a common set of
    message types for APIs to use.
    """

    message: Optional[str] = None
    r"""A developer-facing error message, which should be in English. Any
    user-facing error message should be localized and sent in the
    google.rpc.Status.details field, or localized by the client.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["code", "details", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
