# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TranscriptionConfigParam(TypedDict):
    r"""Configuration for speech recognition (transcription)."""

    adaptation_phrases: NotRequired[List[str]]
    r"""Optional. A list of phrases to bias the ASR model towards."""
    custom_vocabulary: NotRequired[List[str]]
    r"""Optional. A list of custom vocabulary phrases to bias the speech recognition model
    toward recognizing specific terms.
    """
    diarization_mode: NotRequired[str]
    r"""Optional. Configures speaker diarization. Supported values: \"speaker\"."""
    language_codes: NotRequired[List[str]]
    r"""Optional. BCP-47 language codes providing hints about the languages present in the
    audio. If omitted or empty, defaults to automatic language detection.
    """
    timestamp_granularities: NotRequired[List[str]]
    r"""Optional. The granularity of timestamps to include in the transcription output.
    Supported values: \"word\". If empty, no timestamps are generated.
    """


class TranscriptionConfig(BaseModel):
    r"""Configuration for speech recognition (transcription)."""

    adaptation_phrases: Annotated[
        Optional[List[str]],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ] = None
    r"""Optional. A list of phrases to bias the ASR model towards."""

    custom_vocabulary: Optional[List[str]] = None
    r"""Optional. A list of custom vocabulary phrases to bias the speech recognition model
    toward recognizing specific terms.
    """

    diarization_mode: Optional[str] = None
    r"""Optional. Configures speaker diarization. Supported values: \"speaker\"."""

    language_codes: Optional[List[str]] = None
    r"""Optional. BCP-47 language codes providing hints about the languages present in the
    audio. If omitted or empty, defaults to automatic language detection.
    """

    timestamp_granularities: Optional[List[str]] = None
    r"""Optional. The granularity of timestamps to include in the transcription output.
    Supported values: \"word\". If empty, no timestamps are generated.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "adaptation_phrases",
                "custom_vocabulary",
                "diarization_mode",
                "language_codes",
                "timestamp_granularities",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
