# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from ...utils import validate_const
from .urlcontextresult import URLContextResult, URLContextResultParam
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class URLContextResultDeltaTypedDict(TypedDict):
    result: List[URLContextResultParam]
    is_error: NotRequired[bool]
    signature: NotRequired[str]
    r"""A signature hash for backend validation."""
    type: Literal["url_context_result"]


class URLContextResultDelta(BaseModel):
    result: List[URLContextResult]

    is_error: Optional[bool] = None

    signature: Optional[str] = None
    r"""A signature hash for backend validation."""

    type: Annotated[
        Annotated[
            Literal["url_context_result"],
            AfterValidator(validate_const("url_context_result")),
        ],
        pydantic.Field(alias="type"),
    ] = "url_context_result"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["is_error", "signature"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    URLContextResultDelta.model_rebuild()
except NameError:
    pass
