# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel
from ...utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class URLContextParam(TypedDict):
    r"""A tool that can be used by the model to fetch URL context."""

    type: Literal["url_context"]


class URLContext(BaseModel):
    r"""A tool that can be used by the model to fetch URL context."""

    type: Annotated[
        Annotated[
            Literal["url_context"], AfterValidator(validate_const("url_context"))
        ],
        pydantic.Field(alias="type"),
    ] = "url_context"


try:
    URLContext.model_rebuild()
except NameError:
    pass
