# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from ...utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


VideoResponseFormatAspectRatio = Union[
    Literal[
        "16:9",
        "9:16",
    ],
    UnrecognizedStr,
]
r"""The aspect ratio for the video output."""


VideoResponseFormatDelivery = Union[
    Literal[
        "inline",
        "uri",
    ],
    UnrecognizedStr,
]
r"""The delivery mode for the video output."""


class VideoResponseFormatParam(TypedDict):
    r"""Configuration for video output format."""

    aspect_ratio: NotRequired[VideoResponseFormatAspectRatio]
    r"""The aspect ratio for the video output."""
    delivery: NotRequired[VideoResponseFormatDelivery]
    r"""The delivery mode for the video output."""
    duration: NotRequired[str]
    r"""The duration for the video output."""
    gcs_uri: NotRequired[str]
    r"""The Cloud Storage URI to store the video output. Required for Vertex if
    delivery mode is URI.
    """
    type: Literal["video"]


class VideoResponseFormat(BaseModel):
    r"""Configuration for video output format."""

    aspect_ratio: Optional[VideoResponseFormatAspectRatio] = None
    r"""The aspect ratio for the video output."""

    delivery: Optional[VideoResponseFormatDelivery] = None
    r"""The delivery mode for the video output."""

    duration: Optional[str] = None
    r"""The duration for the video output."""

    gcs_uri: Optional[str] = None
    r"""The Cloud Storage URI to store the video output. Required for Vertex if
    delivery mode is URI.
    """

    type: Annotated[
        Annotated[Literal["video"], AfterValidator(validate_const("video"))],
        pydantic.Field(alias="type"),
    ] = "video"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["aspect_ratio", "delivery", "duration", "gcs_uri"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    VideoResponseFormat.model_rebuild()
except NameError:
    pass
