# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class WebhookConfigParam(TypedDict):
    r"""Message for configuring webhook events for a request."""

    uris: NotRequired[List[str]]
    r"""Optional. If set, these webhook URIs will be used for webhook events instead of the
    registered webhooks.
    """
    user_metadata: NotRequired[Dict[str, Any]]
    r"""Optional. The user metadata that will be returned on each event emission to the
    webhooks.
    """


class WebhookConfig(BaseModel):
    r"""Message for configuring webhook events for a request."""

    uris: Optional[List[str]] = None
    r"""Optional. If set, these webhook URIs will be used for webhook events instead of the
    registered webhooks.
    """

    user_metadata: Optional[Dict[str, Any]] = None
    r"""Optional. The user metadata that will be returned on each event emission to the
    webhooks.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["uris", "user_metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
