# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from ...utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WordInfoParam(TypedDict):
    r"""Word-level ASR annotation for transcription output.
    Carries the word text, optional timing, and optional speaker attribution.
    """

    end_index: NotRequired[int]
    r"""End of the attributed segment, exclusive."""
    end_offset: NotRequired[str]
    r"""End offset in time of the word relative to the start of the audio.
    Present when timestamp_granularities contains \"word\".
    """
    speaker: NotRequired[str]
    r"""Optional. Speaker label for this word (e.g. \"spk_1\", \"spk_2\").
    Present when diarization_mode is set in TranscriptionConfig.
    """
    start_index: NotRequired[int]
    r"""Start of segment of the response that is attributed to this source.

    Index indicates the start of the segment, measured in bytes.
    """
    start_offset: NotRequired[str]
    r"""Start offset in time of the word relative to the start of the audio.
    Present when timestamp_granularities contains \"word\".
    """
    text: NotRequired[str]
    r"""The transcribed word."""
    type: Literal["word_info"]


class WordInfo(BaseModel):
    r"""Word-level ASR annotation for transcription output.
    Carries the word text, optional timing, and optional speaker attribution.
    """

    end_index: Optional[int] = None
    r"""End of the attributed segment, exclusive."""

    end_offset: Optional[str] = None
    r"""End offset in time of the word relative to the start of the audio.
    Present when timestamp_granularities contains \"word\".
    """

    speaker: Optional[str] = None
    r"""Optional. Speaker label for this word (e.g. \"spk_1\", \"spk_2\").
    Present when diarization_mode is set in TranscriptionConfig.
    """

    start_index: Optional[int] = None
    r"""Start of segment of the response that is attributed to this source.

    Index indicates the start of the segment, measured in bytes.
    """

    start_offset: Optional[str] = None
    r"""Start offset in time of the word relative to the start of the audio.
    Present when timestamp_granularities contains \"word\".
    """

    text: Optional[str] = None
    r"""The transcribed word."""

    type: Annotated[
        Annotated[Literal["word_info"], AfterValidator(validate_const("word_info"))],
        pydantic.Field(alias="type"),
    ] = "word_info"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "end_index",
                "end_offset",
                "speaker",
                "start_index",
                "start_offset",
                "text",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    WordInfo.model_rebuild()
except NameError:
    pass
