# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from ..utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .cancelinteractionbyid import (
        CancelInteractionByIDGlobals,
        CancelInteractionByIDGlobalsTypedDict,
        CancelInteractionByIDRequest,
        CancelInteractionByIDRequestParam,
    )
    from .createagent import (
        CreateAgentGlobals,
        CreateAgentGlobalsTypedDict,
        CreateAgentRequest,
        CreateAgentRequestParam,
    )
    from .createenvironment import (
        CreateEnvironmentGlobals,
        CreateEnvironmentGlobalsTypedDict,
        CreateEnvironmentRequest,
        CreateEnvironmentRequestParam,
    )
    from .createinteraction import (
        CreateInteractionGlobals,
        CreateInteractionGlobalsTypedDict,
        CreateInteractionRequest,
        CreateInteractionRequestBody,
        CreateInteractionRequestBodyParam,
        CreateInteractionRequestParam,
        CreateInteractionResponse,
        CreateInteractionResponseTypedDict,
    )
    from .createtrigger import (
        CreateTriggerGlobals,
        CreateTriggerGlobalsTypedDict,
        CreateTriggerRequest,
        CreateTriggerRequestParam,
    )
    from .createwebhook import (
        CreateWebhookGlobals,
        CreateWebhookGlobalsTypedDict,
        CreateWebhookRequest,
        CreateWebhookRequestParam,
    )
    from .deleteagent import (
        DeleteAgentGlobals,
        DeleteAgentGlobalsTypedDict,
        DeleteAgentRequest,
        DeleteAgentRequestParam,
    )
    from .deleteenvironment import (
        DeleteEnvironmentGlobals,
        DeleteEnvironmentGlobalsTypedDict,
        DeleteEnvironmentRequest,
        DeleteEnvironmentRequestParam,
    )
    from .deleteinteraction import (
        DeleteInteractionGlobals,
        DeleteInteractionGlobalsTypedDict,
        DeleteInteractionRequest,
        DeleteInteractionRequestParam,
    )
    from .deletetrigger import (
        DeleteTriggerGlobals,
        DeleteTriggerGlobalsTypedDict,
        DeleteTriggerRequest,
        DeleteTriggerRequestParam,
    )
    from .deletewebhook import (
        DeleteWebhookGlobals,
        DeleteWebhookGlobalsTypedDict,
        DeleteWebhookRequest,
        DeleteWebhookRequestParam,
    )
    from .getagent import (
        GetAgentGlobals,
        GetAgentGlobalsTypedDict,
        GetAgentRequest,
        GetAgentRequestParam,
    )
    from .getenvironment import (
        GetEnvironmentGlobals,
        GetEnvironmentGlobalsTypedDict,
        GetEnvironmentRequest,
        GetEnvironmentRequestParam,
    )
    from .getinteractionbyid import (
        GetInteractionByIDGlobals,
        GetInteractionByIDGlobalsTypedDict,
        GetInteractionByIDRequest,
        GetInteractionByIDRequestParam,
        GetInteractionByIDResponse,
        GetInteractionByIDResponseTypedDict,
    )
    from .gettrigger import (
        GetTriggerGlobals,
        GetTriggerGlobalsTypedDict,
        GetTriggerRequest,
        GetTriggerRequestParam,
    )
    from .getwebhook import (
        GetWebhookGlobals,
        GetWebhookGlobalsTypedDict,
        GetWebhookRequest,
        GetWebhookRequestParam,
    )
    from .listagents import (
        ListAgentsGlobals,
        ListAgentsGlobalsTypedDict,
        ListAgentsRequest,
        ListAgentsRequestParam,
    )
    from .listenvironments import (
        ListEnvironmentsGlobals,
        ListEnvironmentsGlobalsTypedDict,
        ListEnvironmentsRequest,
        ListEnvironmentsRequestParam,
    )
    from .listtriggerexecutions import (
        ListTriggerExecutionsGlobals,
        ListTriggerExecutionsGlobalsTypedDict,
        ListTriggerExecutionsRequest,
        ListTriggerExecutionsRequestParam,
    )
    from .listtriggers import (
        ListTriggersGlobals,
        ListTriggersGlobalsTypedDict,
        ListTriggersRequest,
        ListTriggersRequestParam,
    )
    from .listwebhooks import (
        ListWebhooksGlobals,
        ListWebhooksGlobalsTypedDict,
        ListWebhooksRequest,
        ListWebhooksRequestParam,
    )
    from .pingwebhook import (
        PingWebhookGlobals,
        PingWebhookGlobalsTypedDict,
        PingWebhookRequest,
        PingWebhookRequestParam,
    )
    from .rotatesigningsecret import (
        RotateSigningSecretGlobals,
        RotateSigningSecretGlobalsTypedDict,
        RotateSigningSecretRequest,
        RotateSigningSecretRequestParam,
    )
    from .runtrigger import (
        RunTriggerGlobals,
        RunTriggerGlobalsTypedDict,
        RunTriggerRequest,
        RunTriggerRequestParam,
    )
    from .updatetrigger import (
        UpdateTriggerGlobals,
        UpdateTriggerGlobalsTypedDict,
        UpdateTriggerRequest,
        UpdateTriggerRequestParam,
    )
    from .updatewebhook import (
        UpdateWebhookGlobals,
        UpdateWebhookGlobalsTypedDict,
        UpdateWebhookRequest,
        UpdateWebhookRequestParam,
    )
    from . import internal

__all__ = [
    "CancelInteractionByIDGlobals",
    "CancelInteractionByIDGlobalsTypedDict",
    "CancelInteractionByIDRequest",
    "CancelInteractionByIDRequestParam",
    "CreateAgentGlobals",
    "CreateAgentGlobalsTypedDict",
    "CreateAgentRequest",
    "CreateAgentRequestParam",
    "CreateEnvironmentGlobals",
    "CreateEnvironmentGlobalsTypedDict",
    "CreateEnvironmentRequest",
    "CreateEnvironmentRequestParam",
    "CreateInteractionGlobals",
    "CreateInteractionGlobalsTypedDict",
    "CreateInteractionRequest",
    "CreateInteractionRequestBody",
    "CreateInteractionRequestBodyParam",
    "CreateInteractionRequestParam",
    "CreateInteractionResponse",
    "CreateInteractionResponseTypedDict",
    "CreateTriggerGlobals",
    "CreateTriggerGlobalsTypedDict",
    "CreateTriggerRequest",
    "CreateTriggerRequestParam",
    "CreateWebhookGlobals",
    "CreateWebhookGlobalsTypedDict",
    "CreateWebhookRequest",
    "CreateWebhookRequestParam",
    "DeleteAgentGlobals",
    "DeleteAgentGlobalsTypedDict",
    "DeleteAgentRequest",
    "DeleteAgentRequestParam",
    "DeleteEnvironmentGlobals",
    "DeleteEnvironmentGlobalsTypedDict",
    "DeleteEnvironmentRequest",
    "DeleteEnvironmentRequestParam",
    "DeleteInteractionGlobals",
    "DeleteInteractionGlobalsTypedDict",
    "DeleteInteractionRequest",
    "DeleteInteractionRequestParam",
    "DeleteTriggerGlobals",
    "DeleteTriggerGlobalsTypedDict",
    "DeleteTriggerRequest",
    "DeleteTriggerRequestParam",
    "DeleteWebhookGlobals",
    "DeleteWebhookGlobalsTypedDict",
    "DeleteWebhookRequest",
    "DeleteWebhookRequestParam",
    "GetAgentGlobals",
    "GetAgentGlobalsTypedDict",
    "GetAgentRequest",
    "GetAgentRequestParam",
    "GetEnvironmentGlobals",
    "GetEnvironmentGlobalsTypedDict",
    "GetEnvironmentRequest",
    "GetEnvironmentRequestParam",
    "GetInteractionByIDGlobals",
    "GetInteractionByIDGlobalsTypedDict",
    "GetInteractionByIDRequest",
    "GetInteractionByIDRequestParam",
    "GetInteractionByIDResponse",
    "GetInteractionByIDResponseTypedDict",
    "GetTriggerGlobals",
    "GetTriggerGlobalsTypedDict",
    "GetTriggerRequest",
    "GetTriggerRequestParam",
    "GetWebhookGlobals",
    "GetWebhookGlobalsTypedDict",
    "GetWebhookRequest",
    "GetWebhookRequestParam",
    "ListAgentsGlobals",
    "ListAgentsGlobalsTypedDict",
    "ListAgentsRequest",
    "ListAgentsRequestParam",
    "ListEnvironmentsGlobals",
    "ListEnvironmentsGlobalsTypedDict",
    "ListEnvironmentsRequest",
    "ListEnvironmentsRequestParam",
    "ListTriggerExecutionsGlobals",
    "ListTriggerExecutionsGlobalsTypedDict",
    "ListTriggerExecutionsRequest",
    "ListTriggerExecutionsRequestParam",
    "ListTriggersGlobals",
    "ListTriggersGlobalsTypedDict",
    "ListTriggersRequest",
    "ListTriggersRequestParam",
    "ListWebhooksGlobals",
    "ListWebhooksGlobalsTypedDict",
    "ListWebhooksRequest",
    "ListWebhooksRequestParam",
    "PingWebhookGlobals",
    "PingWebhookGlobalsTypedDict",
    "PingWebhookRequest",
    "PingWebhookRequestParam",
    "RotateSigningSecretGlobals",
    "RotateSigningSecretGlobalsTypedDict",
    "RotateSigningSecretRequest",
    "RotateSigningSecretRequestParam",
    "RunTriggerGlobals",
    "RunTriggerGlobalsTypedDict",
    "RunTriggerRequest",
    "RunTriggerRequestParam",
    "UpdateTriggerGlobals",
    "UpdateTriggerGlobalsTypedDict",
    "UpdateTriggerRequest",
    "UpdateTriggerRequestParam",
    "UpdateWebhookGlobals",
    "UpdateWebhookGlobalsTypedDict",
    "UpdateWebhookRequest",
    "UpdateWebhookRequestParam",
]

_dynamic_imports: dict[str, str] = {
    "CancelInteractionByIDGlobals": ".cancelinteractionbyid",
    "CancelInteractionByIDGlobalsTypedDict": ".cancelinteractionbyid",
    "CancelInteractionByIDRequest": ".cancelinteractionbyid",
    "CancelInteractionByIDRequestParam": ".cancelinteractionbyid",
    "CreateAgentGlobals": ".createagent",
    "CreateAgentGlobalsTypedDict": ".createagent",
    "CreateAgentRequest": ".createagent",
    "CreateAgentRequestParam": ".createagent",
    "CreateEnvironmentGlobals": ".createenvironment",
    "CreateEnvironmentGlobalsTypedDict": ".createenvironment",
    "CreateEnvironmentRequest": ".createenvironment",
    "CreateEnvironmentRequestParam": ".createenvironment",
    "CreateInteractionGlobals": ".createinteraction",
    "CreateInteractionGlobalsTypedDict": ".createinteraction",
    "CreateInteractionRequest": ".createinteraction",
    "CreateInteractionRequestBody": ".createinteraction",
    "CreateInteractionRequestBodyParam": ".createinteraction",
    "CreateInteractionRequestParam": ".createinteraction",
    "CreateInteractionResponse": ".createinteraction",
    "CreateInteractionResponseTypedDict": ".createinteraction",
    "CreateTriggerGlobals": ".createtrigger",
    "CreateTriggerGlobalsTypedDict": ".createtrigger",
    "CreateTriggerRequest": ".createtrigger",
    "CreateTriggerRequestParam": ".createtrigger",
    "CreateWebhookGlobals": ".createwebhook",
    "CreateWebhookGlobalsTypedDict": ".createwebhook",
    "CreateWebhookRequest": ".createwebhook",
    "CreateWebhookRequestParam": ".createwebhook",
    "DeleteAgentGlobals": ".deleteagent",
    "DeleteAgentGlobalsTypedDict": ".deleteagent",
    "DeleteAgentRequest": ".deleteagent",
    "DeleteAgentRequestParam": ".deleteagent",
    "DeleteEnvironmentGlobals": ".deleteenvironment",
    "DeleteEnvironmentGlobalsTypedDict": ".deleteenvironment",
    "DeleteEnvironmentRequest": ".deleteenvironment",
    "DeleteEnvironmentRequestParam": ".deleteenvironment",
    "DeleteInteractionGlobals": ".deleteinteraction",
    "DeleteInteractionGlobalsTypedDict": ".deleteinteraction",
    "DeleteInteractionRequest": ".deleteinteraction",
    "DeleteInteractionRequestParam": ".deleteinteraction",
    "DeleteTriggerGlobals": ".deletetrigger",
    "DeleteTriggerGlobalsTypedDict": ".deletetrigger",
    "DeleteTriggerRequest": ".deletetrigger",
    "DeleteTriggerRequestParam": ".deletetrigger",
    "DeleteWebhookGlobals": ".deletewebhook",
    "DeleteWebhookGlobalsTypedDict": ".deletewebhook",
    "DeleteWebhookRequest": ".deletewebhook",
    "DeleteWebhookRequestParam": ".deletewebhook",
    "GetAgentGlobals": ".getagent",
    "GetAgentGlobalsTypedDict": ".getagent",
    "GetAgentRequest": ".getagent",
    "GetAgentRequestParam": ".getagent",
    "GetEnvironmentGlobals": ".getenvironment",
    "GetEnvironmentGlobalsTypedDict": ".getenvironment",
    "GetEnvironmentRequest": ".getenvironment",
    "GetEnvironmentRequestParam": ".getenvironment",
    "GetInteractionByIDGlobals": ".getinteractionbyid",
    "GetInteractionByIDGlobalsTypedDict": ".getinteractionbyid",
    "GetInteractionByIDRequest": ".getinteractionbyid",
    "GetInteractionByIDRequestParam": ".getinteractionbyid",
    "GetInteractionByIDResponse": ".getinteractionbyid",
    "GetInteractionByIDResponseTypedDict": ".getinteractionbyid",
    "GetTriggerGlobals": ".gettrigger",
    "GetTriggerGlobalsTypedDict": ".gettrigger",
    "GetTriggerRequest": ".gettrigger",
    "GetTriggerRequestParam": ".gettrigger",
    "GetWebhookGlobals": ".getwebhook",
    "GetWebhookGlobalsTypedDict": ".getwebhook",
    "GetWebhookRequest": ".getwebhook",
    "GetWebhookRequestParam": ".getwebhook",
    "ListAgentsGlobals": ".listagents",
    "ListAgentsGlobalsTypedDict": ".listagents",
    "ListAgentsRequest": ".listagents",
    "ListAgentsRequestParam": ".listagents",
    "ListEnvironmentsGlobals": ".listenvironments",
    "ListEnvironmentsGlobalsTypedDict": ".listenvironments",
    "ListEnvironmentsRequest": ".listenvironments",
    "ListEnvironmentsRequestParam": ".listenvironments",
    "ListTriggerExecutionsGlobals": ".listtriggerexecutions",
    "ListTriggerExecutionsGlobalsTypedDict": ".listtriggerexecutions",
    "ListTriggerExecutionsRequest": ".listtriggerexecutions",
    "ListTriggerExecutionsRequestParam": ".listtriggerexecutions",
    "ListTriggersGlobals": ".listtriggers",
    "ListTriggersGlobalsTypedDict": ".listtriggers",
    "ListTriggersRequest": ".listtriggers",
    "ListTriggersRequestParam": ".listtriggers",
    "ListWebhooksGlobals": ".listwebhooks",
    "ListWebhooksGlobalsTypedDict": ".listwebhooks",
    "ListWebhooksRequest": ".listwebhooks",
    "ListWebhooksRequestParam": ".listwebhooks",
    "PingWebhookGlobals": ".pingwebhook",
    "PingWebhookGlobalsTypedDict": ".pingwebhook",
    "PingWebhookRequest": ".pingwebhook",
    "PingWebhookRequestParam": ".pingwebhook",
    "RotateSigningSecretGlobals": ".rotatesigningsecret",
    "RotateSigningSecretGlobalsTypedDict": ".rotatesigningsecret",
    "RotateSigningSecretRequest": ".rotatesigningsecret",
    "RotateSigningSecretRequestParam": ".rotatesigningsecret",
    "RunTriggerGlobals": ".runtrigger",
    "RunTriggerGlobalsTypedDict": ".runtrigger",
    "RunTriggerRequest": ".runtrigger",
    "RunTriggerRequestParam": ".runtrigger",
    "UpdateTriggerGlobals": ".updatetrigger",
    "UpdateTriggerGlobalsTypedDict": ".updatetrigger",
    "UpdateTriggerRequest": ".updatetrigger",
    "UpdateTriggerRequestParam": ".updatetrigger",
    "UpdateWebhookGlobals": ".updatewebhook",
    "UpdateWebhookGlobalsTypedDict": ".updatewebhook",
    "UpdateWebhookRequest": ".updatewebhook",
    "UpdateWebhookRequestParam": ".updatewebhook",
}

_sub_packages = ["internal"]


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name,
        package=__package__,
        dynamic_imports=_dynamic_imports,
        sub_packages=_sub_packages,
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports, sub_packages=_sub_packages)
