# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ..types import BaseModel, UNSET_SENTINEL
from ..types.webhooks import webhookupdate as webhooks_webhookupdate
from ..utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    RequestMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateWebhookGlobalsTypedDict(TypedDict):
    api_version: NotRequired[str]
    r"""Which version of the API to use."""


class UpdateWebhookGlobals(BaseModel):
    api_version: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Which version of the API to use."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["api_version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateWebhookRequestParam(TypedDict):
    id: str
    r"""Required. The ID of the webhook to update."""
    api_version: NotRequired[str]
    r"""Which version of the API to use."""
    update_mask: NotRequired[str]
    r"""Optional. The list of fields to update."""
    body: NotRequired[webhooks_webhookupdate.WebhookUpdateParam]
    r"""Required. The webhook to update."""


class UpdateWebhookRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Required. The ID of the webhook to update."""

    api_version: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Which version of the API to use."""

    update_mask: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Optional. The list of fields to update."""

    body: Annotated[
        Optional[webhooks_webhookupdate.WebhookUpdate],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
    r"""Required. The webhook to update."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["api_version", "update_mask", "body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
