# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, Optional, Type, TypeVar, overload

import httpx

from .serializers import unmarshal_json, construct_unvalidated
from .. import errors
import json

T = TypeVar("T")


@overload
def unmarshal_json_response(
    typ: Type[T],
    http_res: httpx.Response,
    body: Optional[str] = None,
    validate: bool = True,
) -> T: ...


@overload
def unmarshal_json_response(
    typ: Any,
    http_res: httpx.Response,
    body: Optional[str] = None,
    validate: bool = True,
) -> Any: ...


def unmarshal_json_response(
    typ: Any,
    http_res: httpx.Response,
    body: Optional[str] = None,
    validate: bool = True,
) -> Any:
    if body is None:
        body = http_res.text
    try:
        return unmarshal_json(body, typ)
    except Exception as e:
        if not validate:
            return construct_unvalidated(json.loads(body), typ)
        raise errors.ResponseValidationError(
            "Response validation failed",
            http_res,
            e,
            body,
        ) from e
