# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .genaierror import GenAiError
from typing import Any, TYPE_CHECKING

from ..utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .cancelinteractionbyid import (
        CancelInteractionByIDClientError,
        CancelInteractionByIDClientErrorData,
        CancelInteractionByIDServerError,
        CancelInteractionByIDServerErrorData,
    )
    from .createinteraction import (
        CreateInteractionClientError,
        CreateInteractionClientErrorData,
        CreateInteractionServerError,
        CreateInteractionServerErrorData,
    )
    from .deleteinteraction import (
        DeleteInteractionClientError,
        DeleteInteractionClientErrorData,
        DeleteInteractionServerError,
        DeleteInteractionServerErrorData,
    )
    from .genaidefaulterror import GenAiDefaultError
    from .getinteractionbyid import (
        GetInteractionByIDClientError,
        GetInteractionByIDClientErrorData,
        GetInteractionByIDServerError,
        GetInteractionByIDServerErrorData,
    )
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "CancelInteractionByIDClientError",
    "CancelInteractionByIDClientErrorData",
    "CancelInteractionByIDServerError",
    "CancelInteractionByIDServerErrorData",
    "CreateInteractionClientError",
    "CreateInteractionClientErrorData",
    "CreateInteractionServerError",
    "CreateInteractionServerErrorData",
    "DeleteInteractionClientError",
    "DeleteInteractionClientErrorData",
    "DeleteInteractionServerError",
    "DeleteInteractionServerErrorData",
    "GenAiDefaultError",
    "GenAiError",
    "GetInteractionByIDClientError",
    "GetInteractionByIDClientErrorData",
    "GetInteractionByIDServerError",
    "GetInteractionByIDServerErrorData",
    "NoResponseError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "CancelInteractionByIDClientError": ".cancelinteractionbyid",
    "CancelInteractionByIDClientErrorData": ".cancelinteractionbyid",
    "CancelInteractionByIDServerError": ".cancelinteractionbyid",
    "CancelInteractionByIDServerErrorData": ".cancelinteractionbyid",
    "CreateInteractionClientError": ".createinteraction",
    "CreateInteractionClientErrorData": ".createinteraction",
    "CreateInteractionServerError": ".createinteraction",
    "CreateInteractionServerErrorData": ".createinteraction",
    "DeleteInteractionClientError": ".deleteinteraction",
    "DeleteInteractionClientErrorData": ".deleteinteraction",
    "DeleteInteractionServerError": ".deleteinteraction",
    "DeleteInteractionServerErrorData": ".deleteinteraction",
    "GenAiDefaultError": ".genaidefaulterror",
    "GetInteractionByIDClientError": ".getinteractionbyid",
    "GetInteractionByIDClientErrorData": ".getinteractionbyid",
    "GetInteractionByIDServerError": ".getinteractionbyid",
    "GetInteractionByIDServerErrorData": ".getinteractionbyid",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
