# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from . import GenAiError
from ..types import BaseModel
from ..types.interactions import error as interactions_error
from dataclasses import dataclass, field
import httpx
from typing import Optional


class CancelInteractionByIDServerErrorData(BaseModel):
    error: interactions_error.Error
    r"""Error message from an interaction."""


@dataclass(unsafe_hash=True)
class CancelInteractionByIDServerError(GenAiError):
    r"""Error cancelling interaction"""

    data: CancelInteractionByIDServerErrorData = field(hash=False)

    def __init__(
        self,
        data: CancelInteractionByIDServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class CancelInteractionByIDClientErrorData(BaseModel):
    error: interactions_error.Error
    r"""Error message from an interaction."""


@dataclass(unsafe_hash=True)
class CancelInteractionByIDClientError(GenAiError):
    r"""Error cancelling interaction"""

    data: CancelInteractionByIDClientErrorData = field(hash=False)

    def __init__(
        self,
        data: CancelInteractionByIDClientErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
