# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from ...utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .pingwebhookrequest import PingWebhookRequest, PingWebhookRequestParam
    from .rotatesigningsecretrequest import (
        RevocationBehavior,
        RotateSigningSecretRequest,
        RotateSigningSecretRequestParam,
    )
    from .signingsecret import SigningSecret, SigningSecretTypedDict
    from .webhook import (
        Webhook,
        WebhookInput,
        WebhookInputParam,
        WebhookState,
        WebhookSubscribedEvent,
        WebhookTypedDict,
    )
    from .webhooklistresponse import WebhookListResponse, WebhookListResponseTypedDict
    from .webhookpingresponse import WebhookPingResponse, WebhookPingResponseTypedDict
    from .webhookrotatesigningsecretresponse import (
        WebhookRotateSigningSecretResponse,
        WebhookRotateSigningSecretResponseTypedDict,
    )
    from .webhookupdate import (
        WebhookUpdate,
        WebhookUpdateParam,
        WebhookUpdateState,
        WebhookUpdateSubscribedEvent,
    )

__all__ = [
    "PingWebhookRequest",
    "PingWebhookRequestParam",
    "RevocationBehavior",
    "RotateSigningSecretRequest",
    "RotateSigningSecretRequestParam",
    "SigningSecret",
    "SigningSecretTypedDict",
    "Webhook",
    "WebhookInput",
    "WebhookInputParam",
    "WebhookListResponse",
    "WebhookListResponseTypedDict",
    "WebhookPingResponse",
    "WebhookPingResponseTypedDict",
    "WebhookRotateSigningSecretResponse",
    "WebhookRotateSigningSecretResponseTypedDict",
    "WebhookState",
    "WebhookSubscribedEvent",
    "WebhookTypedDict",
    "WebhookUpdate",
    "WebhookUpdateParam",
    "WebhookUpdateState",
    "WebhookUpdateSubscribedEvent",
]

_dynamic_imports: dict[str, str] = {
    "PingWebhookRequest": ".pingwebhookrequest",
    "PingWebhookRequestParam": ".pingwebhookrequest",
    "RevocationBehavior": ".rotatesigningsecretrequest",
    "RotateSigningSecretRequest": ".rotatesigningsecretrequest",
    "RotateSigningSecretRequestParam": ".rotatesigningsecretrequest",
    "SigningSecret": ".signingsecret",
    "SigningSecretTypedDict": ".signingsecret",
    "Webhook": ".webhook",
    "WebhookInput": ".webhook",
    "WebhookInputParam": ".webhook",
    "WebhookState": ".webhook",
    "WebhookSubscribedEvent": ".webhook",
    "WebhookTypedDict": ".webhook",
    "WebhookListResponse": ".webhooklistresponse",
    "WebhookListResponseTypedDict": ".webhooklistresponse",
    "WebhookPingResponse": ".webhookpingresponse",
    "WebhookPingResponseTypedDict": ".webhookpingresponse",
    "WebhookRotateSigningSecretResponse": ".webhookrotatesigningsecretresponse",
    "WebhookRotateSigningSecretResponseTypedDict": ".webhookrotatesigningsecretresponse",
    "WebhookUpdate": ".webhookupdate",
    "WebhookUpdateParam": ".webhookupdate",
    "WebhookUpdateState": ".webhookupdate",
    "WebhookUpdateSubscribedEvent": ".webhookupdate",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
