# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


RevocationBehavior = Literal[
    "revoke_previous_secrets_after_h24",
    "revoke_previous_secrets_immediately",
]
r"""Optional. The revocation behavior for previous signing secrets."""


class RotateSigningSecretRequestParam(TypedDict):
    r"""Request message for WebhookService.RotateSigningSecret."""

    revocation_behavior: NotRequired[RevocationBehavior]
    r"""Optional. The revocation behavior for previous signing secrets."""


class RotateSigningSecretRequest(BaseModel):
    r"""Request message for WebhookService.RotateSigningSecret."""

    revocation_behavior: Optional[RevocationBehavior] = None
    r"""Optional. The revocation behavior for previous signing secrets."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["revocation_behavior"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
