# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SigningSecretTypedDict(TypedDict):
    r"""Represents a signing secret used to verify webhook payloads."""

    expire_time: NotRequired[datetime]
    r"""Output only. The expiration date of the signing secret."""
    truncated_secret: NotRequired[str]
    r"""Output only. The truncated version of the signing secret."""


class SigningSecret(BaseModel):
    r"""Represents a signing secret used to verify webhook payloads."""

    expire_time: Optional[datetime] = None
    r"""Output only. The expiration date of the signing secret."""

    truncated_secret: Optional[str] = None
    r"""Output only. The truncated version of the signing secret."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["expire_time", "truncated_secret"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
