# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from .signingsecret import SigningSecret, SigningSecretTypedDict
from datetime import datetime
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


WebhookState = Union[
    Literal[
        "enabled",
        "disabled",
        "disabled_due_to_failed_deliveries",
    ],
    UnrecognizedStr,
]
r"""Output only. The state of the webhook."""


WebhookSubscribedEvent = Union[
    Literal[
        # Batch processing finished successfully.
        "batch.succeeded",
        # Batch has not been processed within the 48h timeframe.
        "batch.expired",
        # Batch job failed.
        "batch.failed",
        # Interaction requires action (e.g., function calling).
        "interaction.requires_action",
        # Interaction completed successfully.
        "interaction.completed",
        # Interaction failed.
        "interaction.failed",
        # Video generation completed.
        "video.generated",
    ],
    UnrecognizedStr,
]


class WebhookTypedDict(TypedDict):
    r"""A Webhook resource."""

    subscribed_events: List[WebhookSubscribedEvent]
    r"""Required. The events that the webhook is subscribed to.
    Available events:
    - batch.succeeded
    - batch.expired
    - batch.failed
    - interaction.requires_action
    - interaction.completed
    - interaction.failed
    - video.generated
    """
    uri: str
    r"""Required. The URI to which webhook events will be sent."""
    create_time: NotRequired[datetime]
    r"""Output only. The timestamp when the webhook was created."""
    id: NotRequired[str]
    r"""Output only. The ID of the webhook."""
    name: NotRequired[str]
    r"""Optional. The user-provided name of the webhook."""
    new_signing_secret: NotRequired[str]
    r"""Output only. The new signing secret for the webhook. Only populated on create."""
    signing_secrets: NotRequired[List[SigningSecretTypedDict]]
    r"""Output only. The signing secrets associated with this webhook."""
    state: NotRequired[WebhookState]
    r"""Output only. The state of the webhook."""
    update_time: NotRequired[datetime]
    r"""Output only. The timestamp when the webhook was last updated."""


class Webhook(BaseModel):
    r"""A Webhook resource."""

    subscribed_events: List[WebhookSubscribedEvent]
    r"""Required. The events that the webhook is subscribed to.
    Available events:
    - batch.succeeded
    - batch.expired
    - batch.failed
    - interaction.requires_action
    - interaction.completed
    - interaction.failed
    - video.generated
    """

    uri: str
    r"""Required. The URI to which webhook events will be sent."""

    create_time: Optional[datetime] = None
    r"""Output only. The timestamp when the webhook was created."""

    id: Optional[str] = None
    r"""Output only. The ID of the webhook."""

    name: Optional[str] = None
    r"""Optional. The user-provided name of the webhook."""

    new_signing_secret: Optional[str] = None
    r"""Output only. The new signing secret for the webhook. Only populated on create."""

    signing_secrets: Optional[List[SigningSecret]] = None
    r"""Output only. The signing secrets associated with this webhook."""

    state: Optional[WebhookState] = None
    r"""Output only. The state of the webhook."""

    update_time: Optional[datetime] = None
    r"""Output only. The timestamp when the webhook was last updated."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "create_time",
                "id",
                "name",
                "new_signing_secret",
                "signing_secrets",
                "state",
                "update_time",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class WebhookInputParam(TypedDict):
    r"""A Webhook resource."""

    subscribed_events: List[WebhookSubscribedEvent]
    r"""Required. The events that the webhook is subscribed to.
    Available events:
    - batch.succeeded
    - batch.expired
    - batch.failed
    - interaction.requires_action
    - interaction.completed
    - interaction.failed
    - video.generated
    """
    uri: str
    r"""Required. The URI to which webhook events will be sent."""
    name: NotRequired[str]
    r"""Optional. The user-provided name of the webhook."""


class WebhookInput(BaseModel):
    r"""A Webhook resource."""

    subscribed_events: List[WebhookSubscribedEvent]
    r"""Required. The events that the webhook is subscribed to.
    Available events:
    - batch.succeeded
    - batch.expired
    - batch.failed
    - interaction.requires_action
    - interaction.completed
    - interaction.failed
    - video.generated
    """

    uri: str
    r"""Required. The URI to which webhook events will be sent."""

    name: Optional[str] = None
    r"""Optional. The user-provided name of the webhook."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
