# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from . import BaseModel, UNSET_SENTINEL
from ..utils import FieldMetadata, SecurityMetadata
import pydantic
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SecurityTypedDict(TypedDict):
    api_key: NotRequired[str]
    r"""Gemini API key sent as x-goog-api-key."""
    access_token: NotRequired[str]
    r"""OAuth access token sent as a bearer Authorization header."""
    default_headers: NotRequired[Dict[str, str]]
    r"""Additional default headers to apply before request-specific headers and auth."""


class Security(BaseModel):
    api_key: Annotated[
        Optional[str],
        pydantic.Field(alias="apiKey"),
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True, scheme_type="http", sub_type="custom", field_name="apiKey"
            )
        ),
    ] = None
    r"""Gemini API key sent as x-goog-api-key."""

    access_token: Annotated[
        Optional[str],
        pydantic.Field(alias="accessToken"),
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="custom",
                field_name="accessToken",
            )
        ),
    ] = None
    r"""OAuth access token sent as a bearer Authorization header."""

    default_headers: Annotated[
        Optional[Dict[str, str]],
        pydantic.Field(alias="defaultHeaders"),
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="custom",
                field_name="defaultHeaders",
            )
        ),
    ] = None
    r"""Additional default headers to apply before request-specific headers and auth."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["apiKey", "accessToken", "defaultHeaders"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Security.model_rebuild()
except NameError:
    pass
